### ISSUE TITLE
[DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by 4u** [bakunyo/bugsnag-sourcemap-webpack-plugin#13]
nodejs 8.1

```
(node:47054) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:127:12)
    at Object.fs.unlink (fs.js:1041:14)
    at /node_modules/bugsnag-sourcemap-webpack-plugin/lib/index.js:134:24
    at Request.callback (/node_modules/bugsnag-sourcemap-webpack-plugin/node_modules/superagent/lib/node/index.js:679:14)
    at IncomingMessage.<anonymous> (/node_modules/bugsnag-sourcemap-webpack-plugin/node_modules/superagent/lib/node/index.js:868:18)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by bakunyo** [comment]
This warning was resolved by https://github.com/bakunyo/bugsnag-sourcemap-webpack-plugin/pull/14 .
Thanks for your contribution @4u .
